export const texts = {
  navigateToSignUp: 'Novo por aqui? Realize seu cadastro',
  emailPlaceholder: 'Email',
  namePlaceholder: 'Nome',
  passwordPlaceholder: 'Senha',
  invalidEmailError: 'Email inválido',
  emailInUseError: 'Esse email já está sendo usado',
  noEmailError: 'Insira seu email',
  nameError: 'Nome muito curto',
  passwordError: 'Senha muito curta',
  noPasswordError: 'Insira sua senha',
  continue: 'Continuar',
  signUp: 'Cadastro',
  login: 'Login',
  wrongUserError: 'Email ou senha incorretos',
  signInAnonimously: 'Entrar como visitante',
  expense: 'Despesa',
  revenue: 'Renda',
  transactionValue: 'Valor da transação',
  description: 'Descrição',
  addTransaction: 'Adicionar transação',
  transactionDescriptionError: 'Insira uma descrição sobre sua transação',
  transactionValueError: 'Insira o valor da transação',
  welcome: 'Bem-vindo,',
  currentBalance: 'Balanço atual',
  logout: 'Sair',
  newTransaction: 'Nova transação',
  category: 'Categoria',
  in: 'Entrada',
  out: 'Saída',
  of: 'de',
  transactions: 'Transações',
};
