export const texts = {
  navigateToSignUp: 'Novo por aqui? Realize seu cadastro',
  emailPlaceholder: 'Email',
  namePlaceholder: 'Nome',
  passwordPlaceholder: 'Senha',
  invalidEmailError: 'Email inválido',
  emailInUseError: 'Esse email já está sendo usado',
  nameError: 'Nome muito curto',
  passwordError: 'Senha muito curta',
  continue: 'Continuar',
  signUp: 'Cadastro',
  login: 'Login',
  wrongUserError: 'Email ou senha incorretos',
  signInAnonimously: 'Entrar como visitante',
  expense: 'Despesa',
  revenue: 'Renda',
  transactionValue: 'Valor da transação',
  description: 'Descrição',
  addTransaction: 'Adicionar transação',
};
